/*
 *
 * Task code generated by SAS Studio 3.8 
 *
 * Generated on '2/22/22, 9:48 PM' 
 * Generated by 'prg21001' 
 * Generated on server 'CTX-VDA-MSB-S06.GROVE.AD.UCONN.EDU' 
 * Generated on SAS platform 'X64_SRV19 WIN' 
 * Generated on SAS version '9.04.01M7P08052020' 
 * Generated on browser 'Mozilla/5.0 (Windows NT 10.0; WOW64; Trident/7.0; rv:11.0) like Gecko' 
 * Generated on web client 'http://localhost:55138/main?locale=en_US&zone=GMT-05%253A00&sutoken=%257B5C55A614-31B4-413C-B7AE-A2514F2163D4%257D&openfile=%255C%255Cmsfs-03.grove.ad.uconn.edu%255Chome%255Cprg21001%255CDesktop%255CTime%2520Series%2520Exploration%25201.ctk' 
 *
 */

ods noproctitle;
ods graphics / imagemap=on;

proc sort data=STSM.HOUSE_PRICES out=Work.preProcessedData;
	by mdate;
run;

%let nhold=12;
%include "&programloc/Macros2.sas" / source2;
%accuracy_prep(indsn=STSM.HOUSE_PRICES, timeid=mdate, series=price, 
    numholdback=&nhold);

proc arima data=Work.preProcessedData plots
    (only)=(series(corr crosscorr) residual(corr normal) 
		forecast(forecastonly)) out=work.out;
	identify var=price(1);
	estimate p=(1) q=(1) method=ML;
	forecast lead=24 back=12 alpha=0.05 id=mdate interval=month;
	outlier;
	run;
quit;

%accuracy(indsn=work.out, timeid=mdate, series=price, 
    numholdback=&nhold);